### ISSUE TITLE
cover art support/tagging support?

### ISSUE THREAD

**Issue by ModestDeer8316** [tim-morriss/pyscrapeTrain#1]
are you able to add cover art support/id3 tagging support?

+ good job on this! works well for the most part, some tracks download halfway through & some fully

**Comment by tim-morriss** [comment]
Hey! Sorry for the late update, just updated the script to include ID3 and artwork support.

If you have an example to a page with tracks downloading halfway can you post it, thanks.

**Comment by ModestDeer8316** [comment]
Thankyou! Tracks that DL'd halfway actually managed to download fully! just the logging in terminal that threw me off thats all.

Also you can get the largest cover size by just removing the size in url, I believe traktrain stores 360x360 as max size
![image](https://user-images.githubusercontent.com/45168911/203329642-cef99083-6738-41d3-bca5-4fa8344cd7ea.png)

**Comment by tim-morriss** [comment]
Great thanks for the tip, I've update the script now to include the larger artworks

**Comment by ModestDeer8316** [comment]
320x320px works but now all the songs are saving just one artwork instead of individual

command used `py scrapetrain.py traktrains.txt -a "TrakTrain"`

**Comment by ModestDeer8316** [comment]
my list of urls if you need to test

> https://traktrain.com/odel
https://traktrain.com/waifu
https://traktrain.com/artemys
https://traktrain.com/bigdog30k
https://traktrain.com/eera
https://traktrain.com/kiryano
https://traktrain.com/lb66
https://traktrain.com/lusi%20rs
https://traktrain.com/mental
https://traktrain.com/funfriend
https://traktrain.com/opal
https://traktrain.com/lovbug
https://traktrain.com/qqqu1ncy
https://traktrain.com/scary
https://traktrain.com/sg37
https://traktrain.com/vagex
https://traktrain.com/vile
https://traktrain.com/vinso
https://traktrain.com/vinsoignatius
https://traktrain.com/rare1
https://traktrain.com/shotti
https://traktrain.com/tahertg
https://traktrain.com/bruh
https://traktrain.com/0k1ro
https://traktrain.com/jxlyy
https://traktrain.com/blush
https://traktrain.com/shinju
https://traktrain.com/silversxo
https://traktrain.com/kuraii
https://traktrain.com/wfbg
https://traktrain.com/methboiswag
https://traktrain.com/cloudbxy1
https://traktrain.com/wstdyth

**Comment by ModestDeer8316** [comment]
yeah still adds the same arts to tracks that have different stuff

**Comment by tim-morriss** [comment]
should be fixed now, sorry about delay
